# Generated by Django 3.2.4 on 2023-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PAID', 'PAID'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
