# Generated by Django 3.2.4 on 2023-04-17 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 22, 39, 12, 846964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='grpc_host',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=30, verbose_name='grpc host'),
        ),
    ]
