# Generated by Django 3.2.4 on 2023-04-17 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230417_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 22, 58, 8, 14735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='grpc_port',
            field=models.IntegerField(blank=True, default=10001, verbose_name='grpc port'),
        ),
        migrations.AlterField(
            model_name='user',
            name='macaroon_path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='macaroon path'),
        ),
    ]
