# Generated by Django 3.2.4 on 2023-04-22 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230417_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 9, 56, 30, 548133, tzinfo=utc)),
        ),
    ]
